# Spring Boot configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pmsdb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
