applicationType: default
defaultPackage: br.com.lucasmancan
testFramework: junit
sourceLanguage: java
buildTool: maven
features: [ annotation-api, app-name, h2, hibernate-validator, http-client, java, java-application, junit, log4j2, maven, netty-server, openapi, readme, shade, yaml ]
