/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bsmvomeia.telas;

import br.com.bsmvomeia.logica.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Mancan
 */
public class TelaListarUsuários extends javax.swing.JFrame {

    public static int telausuarioflag = 0;

    /**
     * Creates new form TelaListarUsuários
     */
    public TelaListarUsuários() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btn_NovoUsuario = new javax.swing.JButton();
        btn_EditUsuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        tblUsuario.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nome"
            }
        ));
        tblUsuario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblUsuario.getTableHeader().setResizingAllowed(false);
        tblUsuario.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblUsuario);

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bsmvomeia/icones/deletebranco.png"))); // NOI18N
        jButton1.setText("  Remover");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_NovoUsuario.setBackground(new java.awt.Color(51, 153, 0));
        btn_NovoUsuario.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        btn_NovoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btn_NovoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bsmvomeia/icones/addbranco.png"))); // NOI18N
        btn_NovoUsuario.setText("  Novo ");
        btn_NovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NovoUsuarioActionPerformed(evt);
            }
        });

        btn_EditUsuario.setBackground(new java.awt.Color(0, 0, 153));
        btn_EditUsuario.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        btn_EditUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btn_EditUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bsmvomeia/icones/editbranco.png"))); // NOI18N
        btn_EditUsuario.setText(" Editar");
        btn_EditUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditUsuarioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuários");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_EditUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_NovoUsuario))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_EditUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btn_NovoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(411, 514));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NovoUsuarioActionPerformed
        if (telausuarioflag == 1) {
            JOptionPane.showMessageDialog(null, "Realize uma operação por vez");
        } else {
            TelaUsuario telaUsuario = new TelaUsuario();
            telausuarioflag = 1;
            telaUsuario.setVisible(true);
        }// TODO add your handling code here:
    }//GEN-LAST:event_btn_NovoUsuarioActionPerformed

    private void btn_EditUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditUsuarioActionPerformed
        if (telausuarioflag == 1) {
            JOptionPane.showMessageDialog(null, "Realize uma operação por vez");
        } else {
            TelaUsuario telaUsuario = new TelaUsuario();
            if (tblUsuario.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "Selecione um Usuario da lista para poder edita-lo");

            } else {

                telaUsuario.setVisible(true);
                Usuario user = new Usuario(TelaUsuario.txtidUsuario, TelaUsuario.txtNomeUsuario, TelaUsuario.txtFoneUsuario, TelaUsuario.txtLoginUsuario, TelaUsuario.txtSenhaUsuario, TelaUsuario.jComboBoxPerfil);
                user.setarCamposUsuario(tblUsuario);
                telausuarioflag = 1;
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EditUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (telausuarioflag == 1) {
            JOptionPane.showMessageDialog(null, "Realize uma operação por vez");
        } else {
            if (tblUsuario.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "Selecione um Usuario da lista para poder remove-lo");

            } else {

                Usuario user = new Usuario(TelaUsuario.txtidUsuario, TelaUsuario.txtNomeUsuario, TelaUsuario.txtFoneUsuario, TelaUsuario.txtLoginUsuario, TelaUsuario.txtSenhaUsuario, TelaUsuario.jComboBoxPerfil);
                user.removerUsuario(tblUsuario);
                user.atualizarTabelaUsuarios(tblUsuario);
                telausuarioflag = 1;
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Usuario user = new Usuario(TelaUsuario.txtidUsuario, TelaUsuario.txtNomeUsuario, TelaUsuario.txtFoneUsuario, TelaUsuario.txtLoginUsuario, TelaUsuario.txtSenhaUsuario, TelaUsuario.jComboBoxPerfil);
        user.atualizarTabelaUsuarios(tblUsuario);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListarUsuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListarUsuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListarUsuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListarUsuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListarUsuários().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_EditUsuario;
    private javax.swing.JButton btn_NovoUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblUsuario;
    // End of variables declaration//GEN-END:variables
}
