/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bsmvomeia.telas;

import br.com.bsmvomeia.logica.ItemVenda;
import br.com.bsmvomeia.logica.Venda;
import javax.swing.JOptionPane;

/**
 *
 * @author Mancan
 */
public class TelaAddProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaAddProduto
     */
    public TelaAddProduto() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ProdutosVenda = new javax.swing.JTable();
        txtPesquisa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_AddProduto = new javax.swing.JButton();
        txtIdProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtquantidade = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        tbl_ProdutosVenda.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        tbl_ProdutosVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Preco"
            }
        ));
        tbl_ProdutosVenda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_ProdutosVenda.getTableHeader().setResizingAllowed(false);
        tbl_ProdutosVenda.getTableHeader().setReorderingAllowed(false);
        tbl_ProdutosVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ProdutosVendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_ProdutosVenda);

        txtPesquisa.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        txtPesquisa.setPreferredSize(new java.awt.Dimension(0, 30));
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pesquisar:");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quantidade:");

        btn_AddProduto.setBackground(new java.awt.Color(51, 153, 0));
        btn_AddProduto.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        btn_AddProduto.setForeground(new java.awt.Color(255, 255, 255));
        btn_AddProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bsmvomeia/icones/okbranco.png"))); // NOI18N
        btn_AddProduto.setText("Salvar");
        btn_AddProduto.setPreferredSize(new java.awt.Dimension(101, 30));
        btn_AddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddProdutoActionPerformed(evt);
            }
        });

        txtIdProduto.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtIdProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdProduto.setEnabled(false);
        txtIdProduto.setPreferredSize(new java.awt.Dimension(0, 30));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Unidade(s)");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Produto");

        txtquantidade.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtquantidade.setModel(new javax.swing.SpinnerNumberModel(1.0f, 0.5f, null, 0.5f));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtIdProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_AddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))))
                .addContainerGap(536, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_AddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(398, 451));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Venda v = new Venda(TelaVenda.txtidClienteVenda, TelaVenda.txtDesconto, TelaVenda.lblValor, TelaVenda.CmbPagamento);
        v.atualizarTabelaProdutosVenda(tbl_ProdutosVenda);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        Venda v = new Venda(TelaVenda.txtidClienteVenda, TelaVenda.txtDesconto, TelaVenda.lblValor, TelaVenda.CmbPagamento);
        v.atualizarTabelaProdutosVendaPesquisa(tbl_ProdutosVenda, txtPesquisa);

        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void tbl_ProdutosVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ProdutosVendaMouseClicked
        // TODO add your handling code here:
        Venda v = new Venda(TelaVenda.txtidClienteVenda, TelaVenda.txtDesconto, TelaVenda.lblValor, TelaVenda.CmbPagamento);

        ItemVenda item = new ItemVenda(TelaVenda.txtidVenda, txtIdProduto, txtquantidade);

        item.setarCamposItemVenda(tbl_ProdutosVenda, txtPesquisa);

    }//GEN-LAST:event_tbl_ProdutosVendaMouseClicked

    private void btn_AddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddProdutoActionPerformed
        //Venda v = new Venda(TelaVenda.txtidClienteVenda, TelaVenda.txtDesconto, TelaVenda.lblValor);

        ItemVenda item = new ItemVenda(TelaVenda.txtidVenda, txtIdProduto, txtquantidade);
        if (!txtIdProduto.getText().isEmpty()) {
            if (TelaVenda.flagItem == 1) {
                int confere = item.alterarItemVenda(TelaVenda.tbl_Itens);
                if (confere > 0) {
                    item.atualizarTabelaItensVenda(TelaVenda.tbl_Itens, TelaVenda.txtidVenda);
                    item.somarColuna(TelaVenda.tbl_Itens, TelaVenda.lblValor, TelaVenda.txtDesconto);
                    this.dispose();
                }

            } else if (TelaVenda.flagItem == 0) {
                int confere = item.adicionarItemVenda(tbl_ProdutosVenda);
                if (confere > 0) {
                    item.atualizarTabelaItensVenda(TelaVenda.tbl_Itens, TelaVenda.txtidVenda);
                    item.somarColuna(TelaVenda.tbl_Itens, TelaVenda.lblValor, TelaVenda.txtDesconto);
                    this.dispose();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto da tabela");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AddProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAddProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAddProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAddProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAddProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAddProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_ProdutosVenda;
    public static javax.swing.JTextField txtIdProduto;
    public static javax.swing.JTextField txtPesquisa;
    public static javax.swing.JSpinner txtquantidade;
    // End of variables declaration//GEN-END:variables
}
