/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bsmvomeia.telas;

import br.com.bsmvomeia.logica.Produto;
import java.text.DecimalFormat;
import javax.swing.JTextField;

/**
 *
 * @author Mancan
 */
public class TelaProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaProduto1
     */
    public TelaProduto() {
        initComponents();
        txtidProduto.setVisible(false);

        getRootPane().setDefaultButton(btn_add_Produto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblmensagem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtidProduto = new javax.swing.JTextField();
        txtnomeProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPrecoProduto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_add_Produto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCustoProduto = new javax.swing.JTextField();
        txtLucroProduto = new javax.swing.JTextField();
        CmbCategoriaProduto = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblmensagem.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        lblmensagem.setForeground(new java.awt.Color(255, 255, 255));
        lblmensagem.setText("Produto");

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome do Produto");

        txtnomeProduto.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        txtnomeProduto.setToolTipText("Digite o Nome do Produto para cadastro");
        txtnomeProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Custo de Fabricação: ");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Margem de Contribuição: ");

        txtPrecoProduto.setEditable(false);
        txtPrecoProduto.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        txtPrecoProduto.setForeground(new java.awt.Color(51, 102, 0));
        txtPrecoProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrecoProduto.setText("0.00");
        txtPrecoProduto.setToolTipText("Valor Final de Venda");
        txtPrecoProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPrecoProduto.setMinimumSize(new java.awt.Dimension(6, 30));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Valor Final de Venda:");

        btn_add_Produto.setBackground(new java.awt.Color(0, 102, 0));
        btn_add_Produto.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btn_add_Produto.setForeground(new java.awt.Color(255, 255, 255));
        btn_add_Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bsmvomeia/icones/okbranco.png"))); // NOI18N
        btn_add_Produto.setText("  Salvar");
        btn_add_Produto.setToolTipText("Salvar Produto");
        btn_add_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_ProdutoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Categoria ");

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 19)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 0));
        jLabel5.setText("R$");
        jLabel5.setPreferredSize(new java.awt.Dimension(28, 30));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 19)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 0));
        jLabel7.setText("R$");
        jLabel7.setPreferredSize(new java.awt.Dimension(28, 30));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 0));
        jLabel8.setText("R$");

        txtCustoProduto.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        txtCustoProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCustoProduto.setText("0.00");
        txtCustoProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCustoProduto.setPreferredSize(new java.awt.Dimension(21, 30));
        txtCustoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustoProdutoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustoProdutoKeyTyped(evt);
            }
        });

        txtLucroProduto.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        txtLucroProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLucroProduto.setText("0.00");
        txtLucroProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtLucroProduto.setPreferredSize(new java.awt.Dimension(21, 30));
        txtLucroProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLucroProdutoKeyReleased(evt);
            }
        });

        CmbCategoriaProduto.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        CmbCategoriaProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Bolos", "Doces", "Pães", "Salgados", "Tortas", "Bebidas" }));
        CmbCategoriaProduto.setToolTipText("Categoria do Produto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblmensagem)
                .addGap(92, 92, 92))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CmbCategoriaProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtnomeProduto)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPrecoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtLucroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCustoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btn_add_Produto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(88, 88, 88)
                                .addComponent(txtidProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblmensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(txtnomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CmbCategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLucroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(txtPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btn_add_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void calcularValorFinal() {

        try {
            double soma = Double.parseDouble(txtCustoProduto.getText()) + Double.parseDouble(txtLucroProduto.getText());
            DecimalFormat formato = new DecimalFormat("#.##");

            txtPrecoProduto.setText(String.valueOf(soma));

        } catch (NumberFormatException e) {
        }

    }
    private void btn_add_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_ProdutoActionPerformed
        Produto prod = new Produto(TelaProduto.txtidProduto, TelaProduto.txtnomeProduto, TelaProduto.CmbCategoriaProduto, TelaProduto.txtCustoProduto, TelaProduto.txtLucroProduto, TelaProduto.txtPrecoProduto);

        //conferindo se tem uma identificação do produto para alteração.
        if (txtidProduto.getText().isEmpty()) {
            int conferirCadastro = prod.adicionarProduto();
            if (conferirCadastro > 0) {
                this.dispose();
                TelaPesquisaProduto.telaProdutoflag = 0;
            }

        } else {
            int conferirEdicao = prod.alterarProduto();
            if (conferirEdicao > 0) {
                this.dispose();
                TelaPesquisaProduto.telaProdutoflag = 0;
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_add_ProdutoActionPerformed

    private void conferirEntrada(JTextField c) {
        if (Float.parseFloat(c.getText()) >= 0 || c.getText().isEmpty()) {
        } else {
            c.setText("0");
        }
    }

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        TelaPesquisaProduto.telaProdutoflag = 1;
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        Produto prod = new Produto(TelaProduto.txtidProduto, TelaProduto.txtnomeProduto, TelaProduto.CmbCategoriaProduto, TelaProduto.txtCustoProduto, TelaProduto.txtLucroProduto, TelaProduto.txtPrecoProduto);
        prod.atualizarTabela("select produtoID as 'ID', nomep as 'Nome', preco as 'Preço de Venda'from produtos");
        TelaPesquisaProduto.telaProdutoflag = 0;
    }//GEN-LAST:event_formWindowClosed

    private void txtCustoProdutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustoProdutoKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustoProdutoKeyTyped

    private void txtCustoProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustoProdutoKeyReleased
        calcularValorFinal();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustoProdutoKeyReleased

    private void txtLucroProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLucroProdutoKeyReleased
        calcularValorFinal();

        // TODO add your handling code here:
    }//GEN-LAST:event_txtLucroProdutoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaProduto().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> CmbCategoriaProduto;
    private javax.swing.JButton btn_add_Produto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lblmensagem;
    public static javax.swing.JTextField txtCustoProduto;
    public static javax.swing.JTextField txtLucroProduto;
    public static javax.swing.JTextField txtPrecoProduto;
    public static javax.swing.JTextField txtidProduto;
    public static javax.swing.JTextField txtnomeProduto;
    // End of variables declaration//GEN-END:variables
}
