/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bsmvomeia.telas;

import br.com.bsmvomeia.logica.Cliente;
import br.com.bsmvomeia.logica.Produto;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.text.html.HTML;

/**
 *
 * @author Mancan
 */
public class TelaPesquisaCliente extends javax.swing.JFrame {

    public static int telaClienteflag = 0;

    /**
     * Creates new form TelaPesquisaCliente
     */
    public TelaPesquisaCliente() {
        initComponents();

        tabelaPesquisa.getColumnModel().getColumn(0).setMaxWidth(0);
        tabelaPesquisa.getColumnModel().getColumn(0).setMinWidth(0);
        tabelaPesquisa.getColumnModel().getColumn(0).setPreferredWidth(0);
        tabelaPesquisa.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabelaPesquisa.getColumnModel().getColumn(2).setPreferredWidth(30);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPesquisa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_edit_Produto = new javax.swing.JButton();
        btn_del_Produto = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPesquisa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        txtPesquisa.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtPesquisa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPesquisa.setPreferredSize(new java.awt.Dimension(6, 30));
        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bsmvomeia/icones/if_search_32.png"))); // NOI18N
        jLabel5.setToolTipText("Digite um nome no Campo à esquerda.");

        btn_edit_Produto.setBackground(new java.awt.Color(0, 51, 204));
        btn_edit_Produto.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        btn_edit_Produto.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit_Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bsmvomeia/icones/editbranco.png"))); // NOI18N
        btn_edit_Produto.setText("  Editar");
        btn_edit_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_ProdutoActionPerformed(evt);
            }
        });

        btn_del_Produto.setBackground(new java.awt.Color(204, 0, 0));
        btn_del_Produto.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        btn_del_Produto.setForeground(new java.awt.Color(255, 255, 255));
        btn_del_Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bsmvomeia/icones/deletebranco.png"))); // NOI18N
        btn_del_Produto.setText(" Remover");
        btn_del_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_del_ProdutoActionPerformed(evt);
            }
        });

        btnNovo.setBackground(new java.awt.Color(0, 153, 0));
        btnNovo.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bsmvomeia/icones/addbranco.png"))); // NOI18N
        btnNovo.setText(" Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        tabelaPesquisa.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        tabelaPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPesquisa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaPesquisa.getTableHeader().setResizingAllowed(false);
        tabelaPesquisa.getTableHeader().setReorderingAllowed(false);
        tabelaPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tabelaPesquisaFocusGained(evt);
            }
        });
        tabelaPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPesquisa);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Clientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_edit_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_del_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1)))
                .addContainerGap(396, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnNovo, btn_del_Produto, btn_edit_Produto});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btn_edit_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btn_del_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(690, 484));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public boolean isCellEditable(int row, int col) {
        // Quais colunas eu não quero deixar editar
        return false;
    }
    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased

        Cliente c = new Cliente(TelaCliente.txtnomeCliente, TelaCliente.txtfoneCliente, TelaCliente.txtenderecoCliente, TelaCliente.txtemailCliente, TelaCliente.txtidCliente, TelaCliente.txtDataCliente);

        c.pesquisarCliente(tabelaPesquisa, txtPesquisa);
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void btn_edit_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_ProdutoActionPerformed
        if (telaClienteflag == 1) {
            JOptionPane.showMessageDialog(null, "Realize uma operação por vez");
        } else {
            if (tabelaPesquisa.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "Selecione um produto da tabela para poder edita-lo");

            } else {
                TelaCliente cli = new TelaCliente();
                Cliente c = new Cliente(TelaCliente.txtnomeCliente, TelaCliente.txtfoneCliente, TelaCliente.txtenderecoCliente, TelaCliente.txtemailCliente, TelaCliente.txtidCliente, TelaCliente.txtDataCliente);
                cli.setVisible(true);
                c.setarCamposCliente(tabelaPesquisa);

            }
        }
    }//GEN-LAST:event_btn_edit_ProdutoActionPerformed

    private void btn_del_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_del_ProdutoActionPerformed
        if (telaClienteflag == 1) {
            JOptionPane.showMessageDialog(null, "Realize uma operação por vez");
        } else {
            if (tabelaPesquisa.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "Selecione um cliente da tabela para poder remove-lo");

            } else {
                Cliente c = new Cliente(TelaCliente.txtnomeCliente, TelaCliente.txtfoneCliente, TelaCliente.txtenderecoCliente, TelaCliente.txtemailCliente, TelaCliente.txtidCliente, TelaCliente.txtDataCliente);
                c.removerCliente(tabelaPesquisa);
                c.atualizarTabelaClientes();

            }
        }   // TODO add your handling code here:
    }//GEN-LAST:event_btn_del_ProdutoActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        if (telaClienteflag == 1) {
            JOptionPane.showMessageDialog(null, "Realize uma operação por vez");
        } else {
            if (this.getTitle().equals("Produtos")) {
                TelaProduto produto;
                produto = new TelaProduto();
                produto.setVisible(true);

            } else if (this.getTitle().equals("Clientes")) {
                TelaCliente telaCliente = new TelaCliente();
                telaCliente.setVisible(true);

            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    private void tabelaPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPesquisaMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaPesquisaMouseClicked

    private void tabelaPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabelaPesquisaFocusGained
        tabelaPesquisa.isCellEditable(ERROR, NORMAL);
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaPesquisaFocusGained

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPesquisaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btn_del_Produto;
    private javax.swing.JButton btn_edit_Produto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabelaPesquisa;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
