/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bsmvomeia.telas;

import br.com.bsmvomeia.logica.Cliente;
import br.com.bsmvomeia.logica.Produto;
import br.com.bsmvomeia.logica.Venda;
import static br.com.bsmvomeia.telas.TelaVenda.txtidClienteVenda;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.text.DateFormat;

import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author Mancan
 */
public class TelaPrincipal extends javax.swing.JFrame {

    public static int controletelaFlag = 0;
    public static int telaFlags = 0;
    public static int flag = 1;
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        /*Rectangle rect = GraphicsEnvironment.getLocalGraphicsEnvironment()
                .getMaximumWindowBounds();
        setSize((int) rect.getWidth(), (int) rect.getHeight());*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        Pn_Elementos = new javax.swing.JPanel();
        txtUser = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblValorFinal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Vendas = new javax.swing.JTable();
        btn_NovaVenda = new javax.swing.JButton();
        btn_editarVenda = new javax.swing.JButton();
        lblApresentação = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btn_menu_addCliente = new javax.swing.JMenuItem();
        btn_Menu_ListarCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btn_Menu_addProduto = new javax.swing.JMenuItem();
        btn_Menu_ListarProduto = new javax.swing.JMenuItem();
        MenuCadUsuarios = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        MenuOpcoes = new javax.swing.JMenu();
        OpcoesSair = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        setIconImages(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Pn_Elementos.setBackground(new java.awt.Color(51, 51, 51));
        Pn_Elementos.setPreferredSize(new java.awt.Dimension(1000, 700));

        txtUser.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        jLabel1.setText("Valor Arrecadado:");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("R$");

        lblValorFinal.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        lblValorFinal.setForeground(new java.awt.Color(0, 153, 0));
        lblValorFinal.setText("0,00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValorFinal)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblValorFinal)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_Vendas.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        tbl_Vendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Data", "Cliente", "Valor"
            }
        ));
        tbl_Vendas.setMaximumSize(new java.awt.Dimension(225, 432));
        tbl_Vendas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_Vendas.getTableHeader().setResizingAllowed(false);
        tbl_Vendas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_Vendas);

        btn_NovaVenda.setBackground(new java.awt.Color(0, 153, 0));
        btn_NovaVenda.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        btn_NovaVenda.setForeground(new java.awt.Color(255, 255, 255));
        btn_NovaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bsmvomeia/icones/addbranco.png"))); // NOI18N
        btn_NovaVenda.setText("  Nova Venda");
        btn_NovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NovaVendaActionPerformed(evt);
            }
        });

        btn_editarVenda.setBackground(new java.awt.Color(0, 153, 153));
        btn_editarVenda.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        btn_editarVenda.setForeground(new java.awt.Color(255, 255, 255));
        btn_editarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bsmvomeia/icones/editbranco.png"))); // NOI18N
        btn_editarVenda.setText("  Editar ");
        btn_editarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarVendaActionPerformed(evt);
            }
        });

        lblApresentação.setFont(new java.awt.Font("Arial Black", 0, 55)); // NOI18N
        lblApresentação.setForeground(new java.awt.Color(255, 255, 255));
        lblApresentação.setText("Vendas");

        javax.swing.GroupLayout Pn_ElementosLayout = new javax.swing.GroupLayout(Pn_Elementos);
        Pn_Elementos.setLayout(Pn_ElementosLayout);
        Pn_ElementosLayout.setHorizontalGroup(
            Pn_ElementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_ElementosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pn_ElementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pn_ElementosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblApresentação)
                        .addGap(207, 207, 207)
                        .addComponent(txtUser)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pn_ElementosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(Pn_ElementosLayout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(btn_editarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_NovaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pn_ElementosLayout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );
        Pn_ElementosLayout.setVerticalGroup(
            Pn_ElementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_ElementosLayout.createSequentialGroup()
                .addGroup(Pn_ElementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pn_ElementosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pn_ElementosLayout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addComponent(lblApresentação)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(Pn_ElementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_editarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_NovaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Clientes");
        jMenu1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N

        btn_menu_addCliente.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btn_menu_addCliente.setText("Novo Cliente");
        btn_menu_addCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_addClienteActionPerformed(evt);
            }
        });
        jMenu1.add(btn_menu_addCliente);

        btn_Menu_ListarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        btn_Menu_ListarCliente.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btn_Menu_ListarCliente.setText("Listar Clientes");
        btn_Menu_ListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Menu_ListarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(btn_Menu_ListarCliente);

        Menu.add(jMenu1);

        jMenu2.setText("Produtos");
        jMenu2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N

        btn_Menu_addProduto.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btn_Menu_addProduto.setText("Novo Produto");
        btn_Menu_addProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Menu_addProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(btn_Menu_addProduto);

        btn_Menu_ListarProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        btn_Menu_ListarProduto.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btn_Menu_ListarProduto.setText("Listar Produtos");
        btn_Menu_ListarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Menu_ListarProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(btn_Menu_ListarProduto);

        Menu.add(jMenu2);

        MenuCadUsuarios.setText("Usuários");
        MenuCadUsuarios.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jMenuItem2.setText("Novo Usuário");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuCadUsuarios.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jMenuItem3.setText("Listar Usuários");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MenuCadUsuarios.add(jMenuItem3);

        Menu.add(MenuCadUsuarios);

        jMenu3.setText("Sobre");
        jMenu3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jMenuItem1.setText("Informações");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jMenuItem5.setText("Ajuda");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        Menu.add(jMenu3);

        MenuOpcoes.setText("Opções");
        MenuOpcoes.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N

        OpcoesSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        OpcoesSair.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        OpcoesSair.setText("Sair");
        OpcoesSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcoesSairActionPerformed(evt);
            }
        });
        MenuOpcoes.add(OpcoesSair);

        Menu.add(MenuOpcoes);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pn_Elementos, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pn_Elementos, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(951, 690));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Venda v = new Venda();
        try {
            v.atualizarTabelaVenda(tbl_Vendas);
            v.somarColuna(tbl_Vendas, lblValorFinal);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);

    }//GEN-LAST:event_formWindowActivated

    private void OpcoesSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcoesSairActionPerformed
        // TODO add your handling code here:
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_OpcoesSairActionPerformed

    private void btn_menu_addClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_addClienteActionPerformed
        TelaCliente tcliente = new TelaCliente();
        tcliente.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_menu_addClienteActionPerformed

    private void btn_Menu_ListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Menu_ListarClienteActionPerformed

        telaFlags = 1;
        // TODO add your handling code here:
        TelaPesquisaCliente pCliente = new TelaPesquisaCliente();
        pCliente.setVisible(true);

        Cliente c = new Cliente(TelaCliente.txtnomeCliente, TelaCliente.txtfoneCliente, TelaCliente.txtenderecoCliente, TelaCliente.txtemailCliente, TelaCliente.txtidCliente, TelaCliente.txtDataCliente);
        c.atualizarTabelaClientes();
    }//GEN-LAST:event_btn_Menu_ListarClienteActionPerformed

    private void btn_Menu_addProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Menu_addProdutoActionPerformed
        TelaProduto p = new TelaProduto();
        p.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Menu_addProdutoActionPerformed

    private void btn_Menu_ListarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Menu_ListarProdutoActionPerformed
        TelaPesquisaProduto produto;
        produto = new TelaPesquisaProduto();
        produto.setVisible(true);
        Produto prod = new Produto(TelaProduto.txtidProduto, TelaProduto.txtnomeProduto, TelaProduto.CmbCategoriaProduto, TelaProduto.txtCustoProduto, TelaProduto.txtLucroProduto, TelaProduto.txtPrecoProduto);
        prod.atualizarTabela("select produtoID as 'ID', nomep as 'Nome', preco as 'Preço de Venda'from produtos");

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Menu_ListarProdutoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaSobre s = new TelaSobre();
        s.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TelaListarUsuários n = new TelaListarUsuários();
        n.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btn_NovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NovaVendaActionPerformed

        if (controletelaFlag == 1) {
            JOptionPane.showMessageDialog(null, "Realize uma operação por vez");
        } else {
            controletelaFlag = 1;
            flag = 1;
            Venda venda = new Venda(TelaVenda.txtidClienteVenda, TelaVenda.txtDesconto, TelaVenda.lblValor, TelaVenda.CmbPagamento);
            venda.adcionarVenda(txtidClienteVenda);

            TelaVenda v = new TelaVenda();
            venda.ultimaVenda(TelaVenda.txtidVenda);
            v.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_NovaVendaActionPerformed

    private void btn_editarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarVendaActionPerformed
        if (controletelaFlag == 1) {
            JOptionPane.showMessageDialog(null, "Realize uma operação por vez");
        } else {
            flag = 2;
            if (tbl_Vendas.getSelectedRow() != -1) {
                TelaVenda venda = new TelaVenda();
                Venda v = new Venda(TelaVenda.txtidClienteVenda, TelaVenda.txtDesconto, TelaVenda.lblValor, TelaVenda.CmbPagamento);
                try {
                    v.setarCamposEditarVenda(tbl_Vendas, TelaVenda.txtidClienteVenda, TelaVenda.txtNomeCliente, TelaVenda.txtData, TelaVenda.lblValor, TelaVenda.txtidVenda);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }

                venda.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma venda para editar");
            }
        } // TODO add your handling code here:
    }//GEN-LAST:event_btn_editarVendaActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        TelaAjuda ajuda = new TelaAjuda();
        ajuda.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    public static javax.swing.JMenu MenuCadUsuarios;
    private javax.swing.JMenu MenuOpcoes;
    private javax.swing.JMenuItem OpcoesSair;
    private javax.swing.JPanel Pn_Elementos;
    private javax.swing.JMenuItem btn_Menu_ListarCliente;
    private javax.swing.JMenuItem btn_Menu_ListarProduto;
    private javax.swing.JMenuItem btn_Menu_addProduto;
    private javax.swing.JButton btn_NovaVenda;
    private javax.swing.JButton btn_editarVenda;
    private javax.swing.JMenuItem btn_menu_addCliente;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApresentação;
    public static javax.swing.JLabel lblValorFinal;
    public static javax.swing.JTable tbl_Vendas;
    public static javax.swing.JLabel txtUser;
    // End of variables declaration//GEN-END:variables
}
