/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bsmvomeia.telas;

import br.com.bsmvomeia.dal.ModuloConexao;
import br.com.bsmvomeia.logica.Cliente;
import br.com.bsmvomeia.logica.Produto;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author Mancan
 */
public class TelaPesquisaProduto extends javax.swing.JFrame {

    public static int telaProdutoflag = 0;

    /**
     * Creates new form TelaPesquisaProduto
     */
    public TelaPesquisaProduto() {
        initComponents();

        // tabelaPesquisa.getColumn("ID").setPreferredWidth(0);
        //tabelaPesquisa.getTableHeader().getColumnModel().getColumn(0).setPreferredWidth(0);
        tabelaPesquisa.getColumnModel().getColumn(0).setMaxWidth(0);
        tabelaPesquisa.getColumnModel().getColumn(0).setMinWidth(0);
        tabelaPesquisa.getColumnModel().getColumn(0).setPreferredWidth(0);
        tabelaPesquisa.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabelaPesquisa.getColumnModel().getColumn(2).setPreferredWidth(20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPesquisa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_edit_Produto = new javax.swing.JButton();
        btn_del_Produto = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPesquisa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        txtPesquisa.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtPesquisa.setToolTipText("Digite um nome para pesquisar");
        txtPesquisa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPesquisa.setPreferredSize(new java.awt.Dimension(6, 30));
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bsmvomeia/icones/if_search_32.png"))); // NOI18N
        jLabel5.setToolTipText("Digite um nome no Campo à esquerda.");

        btn_edit_Produto.setBackground(new java.awt.Color(0, 0, 204));
        btn_edit_Produto.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        btn_edit_Produto.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit_Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bsmvomeia/icones/editbranco.png"))); // NOI18N
        btn_edit_Produto.setText("  Editar");
        btn_edit_Produto.setPreferredSize(new java.awt.Dimension(122, 40));
        btn_edit_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_ProdutoActionPerformed(evt);
            }
        });

        btn_del_Produto.setBackground(new java.awt.Color(255, 0, 0));
        btn_del_Produto.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        btn_del_Produto.setForeground(new java.awt.Color(255, 255, 255));
        btn_del_Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bsmvomeia/icones/deletebranco.png"))); // NOI18N
        btn_del_Produto.setText("  Remover");
        btn_del_Produto.setPreferredSize(new java.awt.Dimension(122, 40));
        btn_del_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_del_ProdutoActionPerformed(evt);
            }
        });

        btnNovo.setBackground(new java.awt.Color(0, 153, 0));
        btnNovo.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bsmvomeia/icones/addbranco.png"))); // NOI18N
        btnNovo.setText("  Novo");
        btnNovo.setPreferredSize(new java.awt.Dimension(122, 40));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        tabelaPesquisa.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        tabelaPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Preço de Venda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPesquisa.setGridColor(new java.awt.Color(51, 51, 51));
        tabelaPesquisa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaPesquisa.getTableHeader().setResizingAllowed(false);
        tabelaPesquisa.getTableHeader().setReorderingAllowed(false);
        tabelaPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPesquisa);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Produtos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(btn_del_Produto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_edit_Produto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(225, 225, 225))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnNovo, btn_del_Produto, btn_edit_Produto});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_edit_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_del_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnNovo, btn_del_Produto, btn_edit_Produto});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(592, 457));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased

        Produto prod = new Produto(TelaProduto.txtidProduto, TelaProduto.txtnomeProduto, TelaProduto.CmbCategoriaProduto, TelaProduto.txtCustoProduto,
                TelaProduto.txtLucroProduto, TelaProduto.txtPrecoProduto);
        prod.pesquisarProduto(tabelaPesquisa, txtPesquisa);

    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void btn_edit_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_ProdutoActionPerformed
        if (TelaPesquisaProduto.telaProdutoflag == 1) {

            JOptionPane.showMessageDialog(null, "Realize uma operação por vez");
        } else {
            if (tabelaPesquisa.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "Selecione um produto da tabela para poder edita-lo");

            } else {
                TelaProduto produto = new TelaProduto(); // TODO add your handling code here:
                Produto prod = new Produto(TelaProduto.txtidProduto, TelaProduto.txtnomeProduto, TelaProduto.CmbCategoriaProduto, TelaProduto.txtCustoProduto, TelaProduto.txtLucroProduto, TelaProduto.txtPrecoProduto);
                prod.setarCampos(tabelaPesquisa);
                produto.setVisible(true);
            }
        }
    }//GEN-LAST:event_btn_edit_ProdutoActionPerformed

    private void btn_del_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_del_ProdutoActionPerformed
        if (TelaPesquisaProduto.telaProdutoflag == 1) {

            JOptionPane.showMessageDialog(null, "Realize uma operação por vez");
        } else {
            Produto prod = new Produto(TelaProduto.txtidProduto, TelaProduto.txtnomeProduto, TelaProduto.CmbCategoriaProduto, TelaProduto.txtCustoProduto, TelaProduto.txtLucroProduto, TelaProduto.txtPrecoProduto);
            if (tabelaPesquisa.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "Selecione um produto da tabela para poder remove-lo");
                TelaPesquisaProduto.telaProdutoflag = 0;
            } else {
                prod.removerProduto(tabelaPesquisa);
                TelaPesquisaProduto.telaProdutoflag = 0;
                prod.atualizarTabela("select produtoID as 'ID', nomep as 'Nome', preco as 'Preço de Venda'from produtos");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_del_ProdutoActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        if (TelaPesquisaProduto.telaProdutoflag == 1) {

            JOptionPane.showMessageDialog(null, "Realize uma operação por vez");
        } else {
            TelaProduto produto;
            produto = new TelaProduto();
            produto.setVisible(true);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    private void tabelaPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPesquisaMouseClicked
        //tabelaPesquisa.isCellEditable(tabelaPesquisa.getRowCount(), tabelaPesquisa.getColumnCount());
        // TODO add your handling code here:

    }//GEN-LAST:event_tabelaPesquisaMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Produto prod = new Produto(TelaProduto.txtidProduto, TelaProduto.txtnomeProduto, TelaProduto.CmbCategoriaProduto, TelaProduto.txtCustoProduto, TelaProduto.txtLucroProduto, TelaProduto.txtPrecoProduto);

        prod.atualizarTabela("select produtoID as 'ID', nomep as 'Nome', preco as 'Preço de Venda'from produtos");

    }//GEN-LAST:event_formWindowActivated

    /*public void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "Nome", "Preço de Venda"};

        conexao.executaSQL(sql);

        try {
            conexao.rs.first();

            do {

            } while (conexao.rs.next());
        }

    }
    catch (Exception e




    )  {
        }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPesquisaProduto().setVisible(true);
            }
        });
    }
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btn_del_Produto;
    private javax.swing.JButton btn_edit_Produto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabelaPesquisa;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
